services:
  db:
    image: postgres:16
    container_name: freezer-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: freezer_item
    ports:
      - "5432:5432"
    volumes:
      - freezer-db-data:/var/lib/postgresql/data

  app:
    build: .
    container_name: app
    ports:
      - "3001:3000"
    environment:
      PORT: 3000
      DB_HOST: db
      DB_USERNAME: user
      DB_PASSWORD: password
      DB_DATABASE: freezer_item
    depends_on:
      - db

volumes:
  freezer-db-data:
